CREATE USER JOAQUIN
IDENTIFIED BY 1234;

GRANT DBA TO JOAQUIN;


/*CREAR UN USUARIO LLAMADO EDUARDO QUE PUEDE CREAR UN USUARIO PERO NO SU CONTRASEÑA.*/

> CREAR EL USUARIO EDUARDO
	CREATE USER EDUARDO IDENTIFIED BY 1234;
> CREAR UN ROL PARA EDUARDO
	CREATE  ROL EDU;
	GRANT CREATE SESSION, CREATE TABLE, SELECT ANY TABLE TO EDU;
> DAR EL ROL A EDUARDO.
	GRANT EDU TO EDUARDO;

COMPROBAR:
	INICIAR SESION COMO EDUARDO
	SELECT * FROM SCOTT.EMP;

/*  EJERCICIO 3 */

	CREATE USER PABLO IDENTIFIED BY PABLO;
	GRANT EDU TO PABLO;
	GRANT CREATE ANY PROCEDURE, CREATE ANY TRIGGER TO PABLO WITH ADMIN OPTION;


/* EJERCICIO 4 */
coche

matri 8 pri
marca 15
año fabri ca numero de 2 digitos

CREATE TABLE COCHE (
	MATRICULA CHAR(8) NOT NULL PRIMARY KEY,
	MARCA VARCHAR2(15),
	AÑO NUMBER(2)
);

mecanicos.
dni 9 caractreres  primaria
nombre 15
puesto 15
parcial 1

CREATE TABLE MECANICOS (
	DNI CHAR(9) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(15),
	PUESTO VARCHAR2(15),
	PARCIAL CHAR(1)
);

t

trabajo
matri llave ajena de coches 8
dni  
horas numero de 3,1 y  mayor de 0.5
fecha tipo date.

CREATE TABLE TRABAJO (
	MATRICULA CHAR(8) NOT NULL PRIMARY KEY,
	DNI CHAR(9) NOT NULL PRIMARY KEY,
	HORAS NUMBER (3,1) DEFAULT 0.5,
	FECHA DATE
	CONSTRAIGN ME_TRA FOREIGN KEY MATRICULA REFERENCES MECANICOS(MATRICULA);
	CONSTRAIGN TRA_CO FOREIGN KEY DNI  REFERENCES COCHES(DNI);
	
);


CREATE TABLE COCHE (
	MATRICULA CHAR(8) NOT NULL PRIMARY KEY CONSTRAINT (,
	MARCA VARCHAR2(15),
	AÑO NUMBER(2)
);


CREATE TABLE MECANICOS (
	DNI CHAR(9) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(15),
	PUESTO VARCHAR2(15),
	PARCIAL CHAR(1)
);

CREATE TABLE TRABAJO (
	MATRICULA CHAR(8) NOT NULL,
	DNI CHAR(9) NOT NULL,
	HORAS NUMBER (3,1) CHECK(HORAS>0.5),
	FECHA DATE,
	CONSTRAINT MA_TRA FOREIGN KEY (MATRICULA) REFERENCES COCHE(MATRICULA)
);

ALTER TABLE COCHE ADD MODELO VARCHAR2(15);
ALTER TABLE TRABAJO ADD CONSTRAINT PK_DOBLE_PRI PRIMARY KEY(DNI,MATRICULA); 
